name: release initial database

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: checkout
        uses: actions/checkout@v7

      - name: install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y clang curl unzip zip  libcurl4-openssl-dev libbrotli-dev libsqlite3-dev nlohmann-json3-dev make

      - name: install zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0

      - name: init
        run: make init

      - name: build
        run: make
      
      - name: download database
        run: curl -fl https://huggingface.co/buckets/Zigistry/Zigistry/tree/zigistry.db?download=true -o ./zigistry.db

      - name: run
        run: ./build/main

      - name: zip
        run: zip -r database.zip ./database

      - name: uploading forlder to release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: database
          name: Database
          files: database.zip
